version: "3"

services:
  distrubstrugal:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./distrubstrugal:/distrubstrugal
    container_name: DISTRU_APP
    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=mydb-dev
      - DB_USER=kheireddine
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: DISTRU_DB
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb-dev
      - POSTGRES_USER=kheireddine
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
