# Generated by Django 3.2 on 2021-05-15 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.CharField(max_length=255)),
                ('nom_article', models.CharField(max_length=255)),
                ('type_de_categorie', models.CharField(max_length=255)),
                ('categorie_interne', models.CharField(max_length=255)),
                ('famille_article', models.CharField(max_length=255)),
                ('unite_mesure', models.CharField(max_length=255)),
                ('sale_ok', models.BooleanField()),
                ('type_article', models.CharField(max_length=255)),
                ('template_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('active', models.BooleanField()),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_commande_odoo', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_description', models.CharField(max_length=255)),
                ('societe', models.CharField(default='Strugal', max_length=255)),
                ('totaleHT', models.FloatField()),
                ('totaleTTC', models.FloatField()),
                ('etat', models.CharField(default='Brouillon ', max_length=255)),
                ('date', models.CharField(default='15/05/2021', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ListArticleCommande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qte', models.IntegerField()),
                ('montant', models.FloatField()),
                ('code_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributeur.article')),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributeur.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Distributeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('tel_fix', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_portable', models.CharField(blank=True, max_length=255, null=True)),
                ('couriel', models.CharField(blank=True, max_length=255, null=True)),
                ('civilite', models.IntegerField(blank=True, null=True)),
                ('site_web', models.CharField(blank=True, max_length=255, null=True)),
                ('rcn', models.CharField(max_length=255)),
                ('date_enregistrement_rc', models.CharField(max_length=255)),
                ('nis', models.CharField(blank=True, max_length=255, null=True)),
                ('ifn', models.CharField(max_length=255)),
                ('art', models.CharField(max_length=255)),
                ('date_debut_activité', models.CharField(blank=True, max_length=255, null=True)),
                ('date_effet', models.CharField(blank=True, max_length=255, null=True)),
                ('date_echeance', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('nbr_facture', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='destributeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributeur.distributeur'),
        ),
    ]
