# Generated by Django 3.2 on 2021-04-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_description', models.CharField(max_length=255)),
                ('societe', models.CharField(default='Strugal', max_length=255)),
                ('totaleHT', models.FloatField()),
                ('totaleTTC', models.FloatField()),
                ('date', models.CharField(default='26/04/2021', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Distributeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('rcn', models.CharField(max_length=255)),
                ('ifn', models.CharField(max_length=255)),
                ('nbr_facture', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ListArticleCommande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_article', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('qte', models.IntegerField()),
                ('montant', models.FloatField()),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributeur.commande')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='destributeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributeur.distributeur'),
        ),
    ]
