# Generated by Django 3.2 on 2021-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(default='27/04/2021', max_length=255),
        ),
    ]
