# Generated by Django 3.2 on 2021-05-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0002_auto_20210518_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='listarticlecommande',
            name='prix_unitaire',
            field=models.IntegerField(default=0),
        ),
    ]
