# Generated by Django 3.2 on 2021-04-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0002_alter_commande_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.CharField(max_length=255)),
                ('nom_article', models.CharField(max_length=255)),
                ('type_de_categorie', models.CharField(max_length=255)),
                ('categorie_interne', models.CharField(max_length=255)),
                ('famille_article', models.CharField(max_length=255)),
                ('unite_mesure', models.CharField(max_length=255)),
                ('sale_ok', models.BooleanField()),
                ('type_article', models.CharField(max_length=255)),
                ('template_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('active', models.BooleanField()),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(default='28/04/2021', max_length=255),
        ),
        migrations.AlterField(
            model_name='listarticlecommande',
            name='code_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributeur.article'),
        ),
    ]
