# Generated by Django 3.2 on 2021-05-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0003_listarticlecommande_prix_unitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(default='20/05/2021', max_length=255),
        ),
    ]
