# Generated by Django 3.2 on 2021-04-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0003_auto_20210428_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(default='29/04/2021', max_length=255),
        ),
    ]
