# Generated by Django 3.2 on 2021-05-02 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributeur', '0004_alter_commande_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeur',
            name='typeProfile',
            field=models.CharField(default='Distributeur', max_length=255),
        ),
        migrations.AddField(
            model_name='distributeur',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(default='02/05/2021', max_length=255),
        ),
    ]
