# Generated by Django 3.2 on 2021-05-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0004_alter_commande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(default='23/05/2021', max_length=255),
        ),
    ]
