# Generated by Django 3.2 on 2021-05-02 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributeur', '0005_auto_20210502_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributeur',
            name='nbr_facture',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distributeur',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
