# Generated by Django 3.2 on 2021-05-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0006_alter_commande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(default='31/05/2021', max_length=255),
        ),
        migrations.AlterField(
            model_name='commande',
            name='etat',
            field=models.CharField(default='Brouillon', max_length=255),
        ),
    ]
