# Generated by Django 3.2 on 2021-05-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0006_auto_20210502_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listarticlecommande',
            name='description',
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(default='03/05/2021', max_length=255),
        ),
    ]
