# Generated by Django 3.2 on 2021-06-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0007_auto_20210531_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(default='01/06/2021', max_length=255),
        ),
    ]
