# Generated by Django 3.2 on 2021-06-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0009_alter_commande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(default='2021-06-02', max_length=255),
        ),
    ]
