# Generated by Django 3.2 on 2021-06-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0013_alter_commande_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='capture',
            field=models.ImageField(blank=True, null=True, upload_to='emailCapture/'),
        ),
    ]
