# Generated by Django 3.2 on 2021-06-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0014_commande_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeur',
            name='id_dist',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(default='2021-06-16', max_length=255),
        ),
    ]
