# Generated by Django 3.2 on 2021-06-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0016_auto_20210621_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(default='2021-06-22', max_length=255),
        ),
    ]
