# Generated by Django 3.2 on 2021-07-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0020_alter_commande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
