# Generated by Django 3.2 on 2021-07-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0021_alter_commande_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='conditionnement',
            field=models.IntegerField(default=0),
        ),
    ]
