# Generated by Django 3.2 on 2021-07-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0022_article_conditionnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='conditionnement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
