# Generated by Django 3.2 on 2021-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0023_alter_article_conditionnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix_unitaire',
            field=models.FloatField(default=0),
        ),
    ]
