# Generated by Django 3.2 on 2022-02-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0026_listedestarifs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Créerfacture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
