# Generated by Django 3.2 on 2022-02-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0027_créerfacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='créerfacture',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
