# Generated by Django 3.2 on 2022-02-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0029_vendeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeCommerciale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
