# Generated by Django 3.2 on 2022-02-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0030_equipecommerciale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipecommerciale',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
