# Generated by Django 3.2 on 2022-02-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0031_alter_equipecommerciale_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimeFiscal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fiscal_position', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
