# Generated by Django 3.2 on 2022-02-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0032_regimefiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='creer_facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributeur.créerfacture'),
        ),
        migrations.AddField(
            model_name='commande',
            name='equipe_commerciale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributeur.equipecommerciale'),
        ),
        migrations.AddField(
            model_name='commande',
            name='list_des_prix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributeur.listedestarifs'),
        ),
        migrations.AddField(
            model_name='commande',
            name='regime_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributeur.regimefiscal'),
        ),
        migrations.AddField(
            model_name='commande',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributeur.vendeur'),
        ),
    ]
