# Generated by Django 3.2 on 2022-02-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributeur', '0033_auto_20220219_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipecommerciale',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
